// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lemacbcmhbykoxehtort.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlbWFjYmNtaGJ5a294ZWh0b3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODQxMDMsImV4cCI6MjA3MDE2MDEwM30.mWUA_NAM7CEsCM9T48TA5CzqhO8TSW0GHDMQyd5wJsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});